# Email sender
service_email: service@ecorp.co
company_name: E-corp
color: '#ffffff'

# Users
users:
  - email: user1@example.com
    # Bcrypted password
    password: $2y$12$P/i4F4a0bDtagnYJR1aRru4y7Gf6c6eBzZBs3UmwDsCBXcMIEoxI6
    
  - email: user2@example.com
    password: $2y$12$P/i4F4a0bDtagnYJR1aRru4y7Gf6c6eBzZBs3UmwDsCBXcMIEoxI6
